FROM python:3.10-slim

# ARG BUILD_DATE
# ARG VCS_REF
# ARG BUILD_VERSION

LABEL maintainer="Roy Sahar"
    #   org.label-schema.build-date=$BUILD_DATE \
    #   org.label-schema.vcs-ref=$VCS_REF \
    #   org.label-schema.version=$BUILD_VERSION \
    #   org.label-schema.name="Status-Page" \
    #   org.label-schema.description="Status-Page Docker Image"

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PATH="/home/status-page/.local/bin:${PATH}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    build-essential \
    libxml2-dev \
    libxslt1-dev \
    libffi-dev \
    libpq-dev \
    libssl-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

WORKDIR /opt/status-page

# Create non-root user
RUN groupadd -r status-page && \
    useradd -r -m -g status-page status-page

COPY --chown=status-page:status-page . .

# Set execute permissions to scripts
RUN chmod 750 /opt/status-page/docker/entrypoint.sh && \
    chmod 750 /opt/status-page/docker/upgrade_docker.sh 

# Switch to non-root user
USER status-page

RUN /opt/status-page/docker/upgrade_docker.sh && \
    chmod 640 /opt/status-page/docker/upgrade_docker.sh  # Remove execute after use

EXPOSE 8000

WORKDIR /opt/status-page/statuspage

ENTRYPOINT ["/opt/status-page/docker/entrypoint.sh"]
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000", "--insecure"]
# CMD ["gunicorn", "--config", "/opt/status-page/docker/gunicorn.py", "statuspage.wsgi:application"]